name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish app
        run: dotnet publish -c Release -o release

      # This prevents GitHub from trying to run Jekyll on our site
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit to GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
